from BaseClasses import ItemClassification

ITEM_NAME_TO_ID = {
    # Artifacts: 1-10
    "Artifact Unlock: Bracelet": 1,
    "Artifact Unlock: Ankh": 2,
    "Artifact Unlock: Urn": 3,
    "Artifact Unlock: Golden Banana": 4,
    "Artifact Unlock: Shield": 5,
    "Artifact Unlock: Chestplate": 6,
    "Artifact Unlock: Golden Treasure": 7,

    # TEMP FILLER
    "filler": 9,

    # Pack Unlocks (Normal): 11-40
    "Dungeon Row: Late-game Pack 1": 11,
    "Dungeon Row: Late-game Pack 2": 12,
    "Dungeon Row: Mid-tier Pack": 13,
    "Dungeon Row: Speedy Pack 1": 14,
    "Dungeon Row: Speedy Pack 2": 15,
    "Dungeon Row: Gem Pack 1": 16,
    "Dungeon Row: Gem Pack 2": 17,
    "Dungeon Row: Gold Pack 1": 18,
    "Dungeon Row: Gold Pack 2": 19,
    "Dungeon Row: Swag Pack 1": 20,
    "Dungeon Row: Swag Pack 2": 21,
    "Dungeon Row: Tome Pack": 22,
    "Dungeon Row: Skill Pack": 23,
    "Dungeon Row: Control Pack": 24,
    "Dungeon Row: Deck Fixing Pack": 25,
    "Dungeon Row: Vitality Pack 1": 26,
    "Dungeon Row: Vitality Pack 2": 27,
    "Dungeon Row: Basic Monster Pack 1": 28,
    "Dungeon Row: Basic Monster Pack 2": 29,
    "Dungeon Row: Basic Monster Pack 3": 30,
    "Dungeon Row: Hard Monster Pack 1": 31,
    "Dungeon Row: Hard Monster Pack 2": 32,
    "Dungeon Row: Device Pack 1": 33,
    "Dungeon Row: Device Pack 2": 34,
    "Dungeon Row: Device Pack 3": 35,

    # Card Unlocks: 41-110
    "Card Unlock: Amulet of Vigor": 41, 
    "Card Unlock: Apothecary": 42, 
    "Card Unlock: Archaeologist": 43, 
    "Card Unlock: Boots of Swiftness": 44, 
    "Card Unlock: Bracers of Agility": 45, 
    "Card Unlock: Brilliance": 46, 
    "Card Unlock: Cleric of the Sun": 47, 
    "Card Unlock: Dead Run": 48, 
    "Card Unlock: Diamond": 49, 
    "Card Unlock: Dragon's Eye": 50, 
    "Card Unlock: Dwarven Peddler": 51, 
    "Card Unlock: Elven Boots": 52, 
    "Card Unlock: Elven Cloak": 53, 
    "Card Unlock: Elven Dagger": 54, 
    "Card Unlock: Emerald": 55, 
    "Card Unlock: Flying Carpet": 56, 
    "Card Unlock: Gem Collector": 57, 
    "Card Unlock: Invoker of the Ancients": 58, 
    "Card Unlock: Kobold Merchant": 59, 
    "Card Unlock: Lucky Coin": 60, 
    "Card Unlock: Master Burglar": 61, 
    "Card Unlock: Mister Whiskers": 62, 
    "Card Unlock: MonkeyBot 3000": 63, 
    "Card Unlock: Move Silently": 64, 
    "Card Unlock: Pickaxe": 65, 
    "Card Unlock: Rebel Captain": 66, 
    "Card Unlock: Rebel Miner": 67, 
    "Card Unlock: Rebel Scout": 68, 
    "Card Unlock: Rebel Soldier": 69, 
    "Card Unlock: Ruby": 70, 
    "Card Unlock: Sapphire": 71, 
    "Card Unlock: Scepter of the Ape Lord": 72, 
    "Card Unlock: Search": 73, 
    "Card Unlock: Silver Spear": 74, 
    "Card Unlock: Singing Sword": 75, 
    "Card Unlock: Sleight of Hand": 76, 
    "Card Unlock: Sneak": 77, 
    "Card Unlock: Swagger": 78, 
    "Card Unlock: Tattle": 79, 
    "Card Unlock: The Duke": 80, 
    "Card Unlock: The Mountain King": 81, 
    "Card Unlock: The Queen of Hearts": 82, 
    "Card Unlock: Treasure Hunter": 83, 
    "Card Unlock: Treasure Map": 84, 
    "Card Unlock: Tunnel Guide": 85, 
    "Card Unlock: Underworld Dealing": 86, 
    "Card Unlock: Wand of Recall": 87, 
    "Card Unlock: Wand of Wind": 88, 
    "Card Unlock: Wizard": 89, 
    "Card Unlock: Animated Door": 90, 
    "Card Unlock: Dragon Shrine": 91, 
    "Card Unlock: Ladder": 92, 
    "Card Unlock: Shrine": 93, 
    "Card Unlock: Teleporter": 94, 
    "Card Unlock: Belcher": 95, 
    "Card Unlock: Cave Troll": 96, 
    "Card Unlock: Crystal Golem": 97, 
    "Card Unlock: Kobold": 98, 
    "Card Unlock: Ogre": 99, 
    "Card Unlock: Orc Grunt": 100, 
    "Card Unlock: Overlord": 101, 
    "Card Unlock: The Vault": 102, 
    "Card Unlock: Watcher": 103,
}


DEFAULT_ITEM_CLASSIFICATIONS = {
    # Artifacts
    "Artifact Unlock: Bracelet": ItemClassification.progression,
    "Artifact Unlock: Ankh": ItemClassification.progression,
    "Artifact Unlock: Urn": ItemClassification.progression,
    "Artifact Unlock: Golden Banana": ItemClassification.progression,
    "Artifact Unlock: Shield": ItemClassification.progression,
    "Artifact Unlock: Chestplate": ItemClassification.progression,
    "Artifact Unlock: Golden Treasure": ItemClassification.progression,

    # TEMP FILLER
    "filler": ItemClassification.filler,

    # Pack Unlocks (Normal)
    "Dungeon Row: Late-game Pack 1": ItemClassification.progression,
    "Dungeon Row: Late-game Pack 2": ItemClassification.progression,
    "Dungeon Row: Mid-tier Pack": ItemClassification.progression,
    "Dungeon Row: Speedy Pack 1": ItemClassification.progression,
    "Dungeon Row: Speedy Pack 2": ItemClassification.progression,
    "Dungeon Row: Gem Pack 1": ItemClassification.progression,
    "Dungeon Row: Gem Pack 2": ItemClassification.progression,
    "Dungeon Row: Gold Pack 1": ItemClassification.progression,
    "Dungeon Row: Gold Pack 2": ItemClassification.progression,
    "Dungeon Row: Swag Pack 1": ItemClassification.progression,
    "Dungeon Row: Swag Pack 2": ItemClassification.progression,
    "Dungeon Row: Tome Pack": ItemClassification.progression,
    "Dungeon Row: Skill Pack": ItemClassification.progression,
    "Dungeon Row: Control Pack": ItemClassification.progression,
    "Dungeon Row: Deck Fixing Pack": ItemClassification.progression,
    "Dungeon Row: Vitality Pack 1": ItemClassification.progression,
    "Dungeon Row: Vitality Pack 2": ItemClassification.progression,
    "Dungeon Row: Basic Monster Pack 1": ItemClassification.progression,
    "Dungeon Row: Basic Monster Pack 2": ItemClassification.progression,
    "Dungeon Row: Basic Monster Pack 3": ItemClassification.progression,
    "Dungeon Row: Hard Monster Pack 1": ItemClassification.progression,
    "Dungeon Row: Hard Monster Pack 2": ItemClassification.progression,
    "Dungeon Row: Device Pack 1": ItemClassification.progression,
    "Dungeon Row: Device Pack 2": ItemClassification.progression,
    "Dungeon Row: Device Pack 3": ItemClassification.progression,

   # Card Unlocks
    "Card Unlock: Amulet of Vigor": ItemClassification.progression, 
    "Card Unlock: Apothecary": ItemClassification.progression, 
    "Card Unlock: Archaeologist": ItemClassification.progression, 
    "Card Unlock: Boots of Swiftness": ItemClassification.progression, 
    "Card Unlock: Bracers of Agility": ItemClassification.progression, 
    "Card Unlock: Brilliance": ItemClassification.progression, 
    "Card Unlock: Cleric of the Sun": ItemClassification.progression, 
    "Card Unlock: Dead Run": ItemClassification.progression, 
    "Card Unlock: Diamond": ItemClassification.progression, 
    "Card Unlock: Dragon's Eye": ItemClassification.progression, 
    "Card Unlock: Dwarven Peddler": ItemClassification.progression, 
    "Card Unlock: Elven Boots": ItemClassification.progression, 
    "Card Unlock: Elven Cloak": ItemClassification.progression, 
    "Card Unlock: Elven Dagger": ItemClassification.progression, 
    "Card Unlock: Emerald": ItemClassification.progression, 
    "Card Unlock: Flying Carpet": ItemClassification.progression, 
    "Card Unlock: Gem Collector": ItemClassification.progression, 
    "Card Unlock: Invoker of the Ancients": ItemClassification.progression, 
    "Card Unlock: Kobold Merchant": ItemClassification.progression, 
    "Card Unlock: Lucky Coin": ItemClassification.progression, 
    "Card Unlock: Master Burglar": ItemClassification.progression, 
    "Card Unlock: Mister Whiskers": ItemClassification.progression, 
    "Card Unlock: MonkeyBot 3000": ItemClassification.progression, 
    "Card Unlock: Move Silently": ItemClassification.progression, 
    "Card Unlock: Pickaxe": ItemClassification.progression, 
    "Card Unlock: Rebel Captain": ItemClassification.progression, 
    "Card Unlock: Rebel Miner": ItemClassification.progression, 
    "Card Unlock: Rebel Scout": ItemClassification.progression, 
    "Card Unlock: Rebel Soldier": ItemClassification.progression, 
    "Card Unlock: Ruby": ItemClassification.progression, 
    "Card Unlock: Sapphire": ItemClassification.progression, 
    "Card Unlock: Scepter of the Ape Lord": ItemClassification.progression, 
    "Card Unlock: Search": ItemClassification.progression, 
    "Card Unlock: Silver Spear": ItemClassification.progression, 
    "Card Unlock: Singing Sword": ItemClassification.progression, 
    "Card Unlock: Sleight of Hand": ItemClassification.progression, 
    "Card Unlock: Sneak": ItemClassification.progression, 
    "Card Unlock: Swagger": ItemClassification.progression, 
    "Card Unlock: Tattle": ItemClassification.progression, 
    "Card Unlock: The Duke": ItemClassification.progression, 
    "Card Unlock: The Mountain King": ItemClassification.progression, 
    "Card Unlock: The Queen of Hearts": ItemClassification.progression, 
    "Card Unlock: Treasure Hunter": ItemClassification.progression, 
    "Card Unlock: Treasure Map": ItemClassification.progression, 
    "Card Unlock: Tunnel Guide": ItemClassification.progression, 
    "Card Unlock: Underworld Dealing": ItemClassification.progression, 
    "Card Unlock: Wand of Recall": ItemClassification.progression, 
    "Card Unlock: Wand of Wind": ItemClassification.progression, 
    "Card Unlock: Wizard": ItemClassification.progression, 
    "Card Unlock: Animated Door": ItemClassification.progression, 
    "Card Unlock: Dragon Shrine": ItemClassification.progression, 
    "Card Unlock: Ladder": ItemClassification.progression, 
    "Card Unlock: Shrine": ItemClassification.progression, 
    "Card Unlock: Teleporter": ItemClassification.progression, 
    "Card Unlock: Belcher": ItemClassification.progression, 
    "Card Unlock: Cave Troll": ItemClassification.progression, 
    "Card Unlock: Crystal Golem": ItemClassification.progression, 
    "Card Unlock: Kobold": ItemClassification.progression, 
    "Card Unlock: Ogre": ItemClassification.progression, 
    "Card Unlock: Orc Grunt": ItemClassification.progression, 
    "Card Unlock: Overlord": ItemClassification.progression, 
    "Card Unlock: The Vault": ItemClassification.progression, 
    "Card Unlock: Watcher": ItemClassification.progression,    
}

ITEM_TYPES = {
    "artifact_unlock": [
        "Artifact Unlock: Bracelet",
        "Artifact Unlock: Ankh",
        "Artifact Unlock: Urn",
        "Artifact Unlock: Golden Banana",
        "Artifact Unlock: Shield",
        "Artifact Unlock: Chestplate",
        "Artifact Unlock: Golden Treasure",
    ],
    "dungeon_row_pack_normal": [
        "Dungeon Row: Late-game Pack 1",
        "Dungeon Row: Late-game Pack 2",
        "Dungeon Row: Mid-tier Pack",
        "Dungeon Row: Speedy Pack 1",
        "Dungeon Row: Speedy Pack 2",
        "Dungeon Row: Gem Pack 1",
        "Dungeon Row: Gem Pack 2",
        "Dungeon Row: Gold Pack 1",
        "Dungeon Row: Gold Pack 2",
        "Dungeon Row: Swag Pack 1",
        "Dungeon Row: Swag Pack 2",
        "Dungeon Row: Tome Pack",
        "Dungeon Row: Skill Pack",
        "Dungeon Row: Control Pack",
        "Dungeon Row: Deck Fixing Pack",
        "Dungeon Row: Vitality Pack 1",
        "Dungeon Row: Vitality Pack 2",
        "Dungeon Row: Basic Monster Pack 1",
        "Dungeon Row: Basic Monster Pack 2",
        "Dungeon Row: Basic Monster Pack 3",
        "Dungeon Row: Hard Monster Pack 1",
        "Dungeon Row: Hard Monster Pack 2",
        "Dungeon Row: Device Pack 1",
        "Dungeon Row: Device Pack 2",
        "Dungeon Row: Device Pack 3",
    ],
    "dungeon_row_card_unlock": [
        "Card Unlock: Amulet of Vigor", 
        "Card Unlock: Apothecary", 
        "Card Unlock: Archaeologist", 
        "Card Unlock: Boots of Swiftness", 
        "Card Unlock: Bracers of Agility", 
        "Card Unlock: Brilliance", 
        "Card Unlock: Cleric of the Sun", 
        "Card Unlock: Dead Run", 
        "Card Unlock: Diamond", 
        "Card Unlock: Dragon's Eye", 
        "Card Unlock: Dwarven Peddler", 
        "Card Unlock: Elven Boots", 
        "Card Unlock: Elven Cloak", 
        "Card Unlock: Elven Dagger", 
        "Card Unlock: Emerald", 
        "Card Unlock: Flying Carpet", 
        "Card Unlock: Gem Collector", 
        "Card Unlock: Invoker of the Ancients", 
        "Card Unlock: Kobold Merchant", 
        "Card Unlock: Lucky Coin", 
        "Card Unlock: Master Burglar", 
        "Card Unlock: Mister Whiskers", 
        "Card Unlock: MonkeyBot 3000", 
        "Card Unlock: Move Silently", 
        "Card Unlock: Pickaxe", 
        "Card Unlock: Rebel Captain", 
        "Card Unlock: Rebel Miner", 
        "Card Unlock: Rebel Scout", 
        "Card Unlock: Rebel Soldier", 
        "Card Unlock: Ruby", 
        "Card Unlock: Sapphire", 
        "Card Unlock: Scepter of the Ape Lord", 
        "Card Unlock: Search", 
        "Card Unlock: Silver Spear", 
        "Card Unlock: Singing Sword", 
        "Card Unlock: Sleight of Hand", 
        "Card Unlock: Sneak", 
        "Card Unlock: Swagger", 
        "Card Unlock: Tattle", 
        "Card Unlock: The Duke", 
        "Card Unlock: The Mountain King", 
        "Card Unlock: The Queen of Hearts", 
        "Card Unlock: Treasure Hunter", 
        "Card Unlock: Treasure Map", 
        "Card Unlock: Tunnel Guide", 
        "Card Unlock: Underworld Dealing", 
        "Card Unlock: Wand of Recall", 
        "Card Unlock: Wand of Wind", 
        "Card Unlock: Wizard", 
        "Card Unlock: Animated Door", 
        "Card Unlock: Dragon Shrine", 
        "Card Unlock: Ladder", 
        "Card Unlock: Shrine", 
        "Card Unlock: Teleporter", 
        "Card Unlock: Belcher", 
        "Card Unlock: Cave Troll", 
        "Card Unlock: Crystal Golem",
        "Card Unlock: Kobold", 
        "Card Unlock: Ogre", 
        "Card Unlock: Orc Grunt", 
        "Card Unlock: Overlord", 
        "Card Unlock: The Vault", 
        "Card Unlock: Watcher",
    ],
}

