LOCATION_NAME_TO_ID = {
    # artifact exraction: 1-10
    "Artifact Extraction: Bracelet": 1,
    "Artifact Extraction: Ankh": 2,
    "Artifact Extraction: Urn": 3,
    "Artifact Extraction: Golden Banana": 4,
    "Artifact Extraction: Shield": 5,
    "Artifact Extraction: Chestplate": 6,
    "Artifact Extraction: Golden Treasure": 7,

    # rowsanity: 11-80
    "RowSanity: Amulet of Vigor": 11,
    "RowSanity: Apothecary": 12, 
    "RowSanity: Archaeologist": 13, 
    "RowSanity: Boots of Swiftness": 14, 
    "RowSanity: Bracers of Agility": 15, 
    "RowSanity: Brilliance": 16, 
    "RowSanity: Cleric of the Sun": 17, 
    "RowSanity: Dead Run": 18, 
    "RowSanity: Diamond": 19, 
    "RowSanity: Dragon's Eye": 20, 
    "RowSanity: Dwarven Peddler": 21, 
    "RowSanity: Elven Boots": 22, 
    "RowSanity: Elven Cloak": 23, 
    "RowSanity: Elven Dagger": 24, 
    "RowSanity: Emerald": 25, 
    "RowSanity: Flying Carpet": 26, 
    "RowSanity: Gem Collector": 27, 
    "RowSanity: Invoker of the Ancients": 28, 
    "RowSanity: Kobold Merchant": 29, 
    "RowSanity: Lucky Coin": 30, 
    "RowSanity: Master Burglar": 31, 
    "RowSanity: Mister Whiskers": 32, 
    "RowSanity: MonkeyBot 3000": 33, 
    "RowSanity: Move Silently": 34, 
    "RowSanity: Pickaxe": 35, 
    "RowSanity: Rebel Captain": 36, 
    "RowSanity: Rebel Miner": 37, 
    "RowSanity: Rebel Scout": 38, 
    "RowSanity: Rebel Soldier": 39, 
    "RowSanity: Ruby": 40, 
    "RowSanity: Sapphire": 41, 
    "RowSanity: Scepter of the Ape Lord": 42, 
    "RowSanity: Search": 43, 
    "RowSanity: Silver Spear": 44, 
    "RowSanity: Singing Sword": 45, 
    "RowSanity: Sleight of Hand": 46, 
    "RowSanity: Sneak": 47, 
    "RowSanity: Swagger": 48, 
    "RowSanity: Tattle": 49, 
    "RowSanity: The Duke": 50, 
    "RowSanity: The Mountain King": 51, 
    "RowSanity: The Queen of Hearts": 52, 
    "RowSanity: Treasure Hunter": 53, 
    "RowSanity: Treasure Map": 54, 
    "RowSanity: Tunnel Guide": 55, 
    "RowSanity: Underworld Dealing": 56, 
    "RowSanity: Wand of Recall": 57, 
    "RowSanity: Wand of Wind": 58, 
    "RowSanity: Wizard": 59, 
    "RowSanity: Animated Door": 60, 
    "RowSanity: Dragon Shrine": 61, 
    "RowSanity: Ladder": 62, 
    "RowSanity: Shrine": 63, 
    "RowSanity: Teleporter": 64, 
    "RowSanity: Belcher": 65, 
    "RowSanity: Cave Troll": 66, 
    "RowSanity: Crystal Golem": 67, 
    "RowSanity: Kobold": 68, 
    "RowSanity: Ogre": 69, 
    "RowSanity: Orc Grunt": 70, 
    "RowSanity: Overlord": 71, 
    "RowSanity: The Vault": 72, 
    "RowSanity: Watcher": 73,

    # END OF ITEM DICT - used to set the starting value for the bonus row and market
    "end_of_dict": 80
}


LOCATION_TYPES = {
    "artifact_extraction": [
        "Artifact Extraction: Bracelet",
        "Artifact Extraction: Ankh",
        "Artifact Extraction: Urn",
        "Artifact Extraction: Golden Banana",
        "Artifact Extraction: Shield",
        "Artifact Extraction: Chestplate",
        "Artifact Extraction: Golden Treasure",
    ],
    "rowsanity": [
        "RowSanity: Amulet of Vigor", "RowSanity: Apothecary", "RowSanity: Archaeologist", "RowSanity: Boots of Swiftness", "RowSanity: Bracers of Agility", "RowSanity: Brilliance", "RowSanity: Cleric of the Sun", "RowSanity: Dead Run", "RowSanity: Diamond", "RowSanity: Dragon's Eye", "RowSanity: Dwarven Peddler", "RowSanity: Elven Boots", "RowSanity: Elven Cloak", "RowSanity: Elven Dagger", "RowSanity: Emerald", "RowSanity: Flying Carpet", "RowSanity: Gem Collector", "RowSanity: Invoker of the Ancients", "RowSanity: Kobold Merchant", "RowSanity: Lucky Coin", "RowSanity: Master Burglar", "RowSanity: Mister Whiskers", "RowSanity: MonkeyBot 3000", "RowSanity: Move Silently", "RowSanity: Pickaxe", "RowSanity: Rebel Captain", "RowSanity: Rebel Miner", "RowSanity: Rebel Scout", "RowSanity: Rebel Soldier", "RowSanity: Ruby", "RowSanity: Sapphire", "RowSanity: Scepter of the Ape Lord", "RowSanity: Search", "RowSanity: Silver Spear", "RowSanity: Singing Sword", "RowSanity: Sleight of Hand", "RowSanity: Sneak", "RowSanity: Swagger", "RowSanity: Tattle", "RowSanity: The Duke", "RowSanity: The Mountain King", "RowSanity: The Queen of Hearts", "RowSanity: Treasure Hunter", "RowSanity: Treasure Map", "RowSanity: Tunnel Guide", "RowSanity: Underworld Dealing", "RowSanity: Wand of Recall", "RowSanity: Wand of Wind", "RowSanity: Wizard", "RowSanity: Animated Door", "RowSanity: Dragon Shrine", "RowSanity: Ladder", "RowSanity: Shrine", "RowSanity: Teleporter", "RowSanity: Belcher", "RowSanity: Cave Troll", "RowSanity: Crystal Golem", "RowSanity: Kobold", "RowSanity: Ogre", "RowSanity: Orc Grunt", "RowSanity: Overlord", "RowSanity: The Vault", "RowSanity: Watcher"
    ]
}