BONUS_DATA = {
    "dungeon_packs_normal": {
        "Dungeon Row: Late-game Pack 1": ["RowSanity: Move Silently", "RowSanity: Brilliance", "RowSanity: Wand of Recall", "RowSanity: Wand of Wind"],
        "Dungeon Row: Late-game Pack 2": ["RowSanity: Boots of Swiftness", "RowSanity: Move Silently", "RowSanity: Silver Spear", "RowSanity: Wand of Recall"],
        "Dungeon Row: Mid-tier Pack": ["RowSanity: Flying Carpet", "RowSanity: Elven Cloak", "RowSanity: The Queen of Hearts", "RowSanity: Rebel Soldier"],
        "Dungeon Row: Speedy Pack 1": ["RowSanity: Dead Run", "RowSanity: Elven Boots", "RowSanity: Tunnel Guide", "RowSanity: Rebel Captain"],
        "Dungeon Row: Speedy Pack 2": ["RowSanity: Dead Run", "RowSanity: Elven Dagger", "RowSanity: Treasure Hunter", "RowSanity: Rebel Scout"],
        "Dungeon Row: Gem Pack 1": ["RowSanity: Gem Collector", "RowSanity: Emerald", "RowSanity: Sapphire", "RowSanity: Ruby", "RowSanity: Diamond"],
        "Dungeon Row: Gem Pack 2": ["RowSanity: Dragon's Eye", "RowSanity: Emerald", "RowSanity: Sapphire", "RowSanity: Ruby", "RowSanity: Sapphire"],
        "Dungeon Row: Gold Pack 1": ["RowSanity: Search", "RowSanity: Treasure Map", "RowSanity: Dwarven Peddler", "RowSanity: Rebel Miner"],
        "Dungeon Row: Gold Pack 2": ["RowSanity: Search", "RowSanity: The Duke", "RowSanity: Apothecary", "RowSanity: Pickaxe"],
        "Dungeon Row: Swag Pack 1": ["RowSanity: Lucky Coin", "RowSanity: MonkeyBot 3000", "RowSanity: Swagger", "RowSanity: Sneak"],
        "Dungeon Row: Swag Pack 2": ["RowSanity: Lucky Coin", "RowSanity: Scepter of the Ape Lord", "RowSanity: Swagger", "RowSanity: Sneak"],
        "Dungeon Row: Tome Pack": ["RowSanity: Underworld Dealing", "RowSanity: Wizard", "RowSanity: Kobold Merchant", "RowSanity: Pickaxe"],
        "Dungeon Row: Skill Pack": ["RowSanity: Tattle", "RowSanity: Tattle", "RowSanity: Amulet of Vigor", "RowSanity: Archaeologist"],
        "Dungeon Row: Control Pack": ["RowSanity: Silver Spear", "RowSanity: Singing Sword", "RowSanity: Sleight of Hand", "RowSanity: Mister Whiskers"],
        "Dungeon Row: Deck Fixing Pack": ["RowSanity: Master Burglar", "RowSanity: Master Burglar", "RowSanity: Treasure Hunter", "RowSanity: Sleight of Hand"],
        "Dungeon Row: Vitality Pack 1": ["RowSanity: Bracers of Agility", "RowSanity: Cleric of the Sun", "RowSanity: Invoker of the Ancients", "RowSanity: Tunnel Guide"],
        "Dungeon Row: Vitality Pack 2": ["RowSanity: Bracers of Agility", "RowSanity: Cleric of the Sun", "RowSanity: The Mountain King", "RowSanity: Archaeologist"],
        "Dungeon Row: Basic Monster Pack 1": ["RowSanity: Orc Grunt", "RowSanity: Watcher", "RowSanity: Kobold", "RowSanity: Belcher"],
        "Dungeon Row: Basic Monster Pack 2": ["RowSanity: Orc Grunt", "RowSanity: Watcher", "RowSanity: Kobold", "RowSanity: Belcher"],
        "Dungeon Row: Basic Monster Pack 3": ["RowSanity: Orc Grunt", "RowSanity: Watcher", "RowSanity: Kobold", "RowSanity: Animated Door"],
        "Dungeon Row: Hard Monster Pack 1":  ["RowSanity: Crystal Golem", "RowSanity: Ogre", "RowSanity: Overlord", "RowSanity: Cave Troll"],
        "Dungeon Row: Hard Monster Pack 2": ["RowSanity: Crystal Golem", "RowSanity: Ogre", "RowSanity: Overlord", "RowSanity: Animated Door"],
        "Dungeon Row: Device Pack 1": ["RowSanity: Shrine", "RowSanity: Ladder", "RowSanity: Teleporter"],
        "Dungeon Row: Device Pack 2": ["RowSanity: Shrine", "RowSanity: Ladder", "RowSanity: Teleporter"],
        "Dungeon Row: Device Pack 3": ["RowSanity: Shrine", "RowSanity: Dragon Shrine", "RowSanity: Dragon Shrine", "RowSanity: The Vault"],
    },
    "card_list": ["Amulet of Vigor", "Animated Door", "Animated Door", "Apothecary", "Archaeologist", "Archaeologist", "Belcher", "Belcher", "Boots of Swiftness", "Bracers of Agility", "Bracers of Agility", "Brilliance", "Cave Troll", "Cleric of the Sun", "Cleric of the Sun", "Crystal Golem", "Crystal Golem", "Dead Run", "Dead Run", "Diamond", "Dragon Shrine", "Dragon Shrine", "Dragon's Eye", "Dwarven Peddler", "Elven Boots", "Elven Cloak", "Elven Dagger", "Emerald", "Emerald", "Flying Carpet", "Gem Collector", "Invoker of the Ancients", "Kobold", "Kobold", "Kobold", "Kobold Merchant", "Ladder", "Ladder", "Lucky Coin", "Lucky Coin", "Master Burglar", "Master Burglar", "Mister Whiskers", "MonkeyBot 3000", "Move Silently", "Move Silently", "Ogre", "Ogre", "Orc Grunt", "Orc Grunt", "Orc Grunt", "Overlord", "Overlord", "Pickaxe", "Pickaxe", "Rebel Captain", "Rebel Miner", "Rebel Scout", "Rebel Soldier", "Ruby", "Ruby", "Sapphire", "Sapphire", "Sapphire", "Scepter of the Ape Lord", "Search", "Search", "Shrine", "Shrine", "Shrine", "Silver Spear", "Silver Spear", "Singing Sword", "Sleight of Hand", "Sleight of Hand", "Sneak", "Sneak", "Swagger", "Swagger", "Tattle", "Tattle", "Teleporter", "Teleporter", "The Duke", "The Mountain King", "The Queen of Hearts", "The Vault", "Treasure Hunter", "Treasure Hunter", "Treasure Map", "Tunnel Guide", "Tunnel Guide", "Underworld Dealing", "Wand of Recall", "Wand of Recall", "Wand of Wind", "Watcher", "Watcher", "Watcher", "Wizard"],
    "card_list_no_dupe": ["Amulet of Vigor", "Animated Door", "Apothecary", "Archaeologist", "Belcher", "Boots of Swiftness", "Bracers of Agility", "Brilliance", "Cave Troll", "Cleric of the Sun", "Crystal Golem", "Dead Run", "Diamond", "Dragon Shrine", "Dragon's Eye", "Dwarven Peddler", "Elven Boots", "Elven Cloak", "Elven Dagger", "Emerald", "Flying Carpet", "Gem Collector", "Invoker of the Ancients", "Kobold", "Kobold Merchant", "Ladder", "Lucky Coin", "Master Burglar", "Mister Whiskers", "MonkeyBot 3000", "Move Silently", "Ogre", "Orc Grunt", "Overlord", "Pickaxe", "Rebel Captain", "Rebel Miner", "Rebel Scout", "Rebel Soldier", "Ruby", "Sapphire", "Scepter of the Ape Lord", "Search", "Shrine", "Silver Spear", "Singing Sword", "Sleight of Hand", "Sneak", "Swagger", "Tattle", "Teleporter", "The Duke", "The Mountain King", "The Queen of Hearts", "The Vault", "Treasure Hunter", "Treasure Map", "Tunnel Guide", "Underworld Dealing", "Wand of Recall", "Wand of Wind", "Watcher", "Wizard"],
    "rowsanity_rules": {
        "RowSanity: Amulet of Vigor": ["Dungeon Row: Skill Pack"], 
        "RowSanity: Apothecary": ["Dungeon Row: Gold Pack 1"], 
        "RowSanity: Archaeologist": ["Dungeon Row: Skill Pack", "Dungeon Row: Vitality Pack 2"], 
        "RowSanity: Boots of Swiftness": ["Dungeon Row: Late-game Pack 1"], 
        "RowSanity: Bracers of Agility": ["Dungeon Row: Vitality Pack 1", "Dungeon Row: Vitality Pack 2"], 
        "RowSanity: Brilliance": ["Dungeon Row: Late-game Pack 1"], 
        "RowSanity: Cleric of the Sun": ["Dungeon Row: Vitality Pack 1", "Dungeon Row: Vitality Pack 2"], 
        "RowSanity: Dead Run": ["Dungeon Row: Speedy Pack 1", "Dungeon Row: Speedy Pack 2"], 
        "RowSanity: Diamond": ["Dungeon Row: Gem Pack 1"], 
        "RowSanity: Dragon's Eye": ["Dungeon Row: Gem Pack 2"], 
        "RowSanity: Dwarven Peddler": ["Dungeon Row: Gold Pack 1"], 
        "RowSanity: Elven Boots": ["Dungeon Row: Speedy Pack 1"], 
        "RowSanity: Elven Cloak": ["Dungeon Row: Mid-tier Pack"], 
        "RowSanity: Elven Dagger": ["Dungeon Row: Speedy Pack 2"], 
        "RowSanity: Emerald": ["Dungeon Row: Gem Pack 1", "Dungeon Row: Gem Pack 2"], 
        "RowSanity: Flying Carpet": ["Dungeon Row: Mid-tier Pack"], 
        "RowSanity: Gem Collector": ["Dungeon Row: Gem Pack 1"], 
        "RowSanity: Invoker of the Ancients": ["Dungeon Row: Vitality Pack 1"], 
        "RowSanity: Kobold Merchant": ["Dungeon Row: Tome Pack"], 
        "RowSanity: Lucky Coin": ["Dungeon Row: Swag Pack 1", "Dungeon Row: Swag Pack 2"], 
        "RowSanity: Master Burglar": ["Dungeon Row: Deck Fixing Pack"], 
        "RowSanity: Mister Whiskers": ["Dungeon Row: Control Pack"], 
        "RowSanity: MonkeyBot 3000": ["Dungeon Row: Swag Pack 1"], 
        "RowSanity: Move Silently": ["Dungeon Row: Late-game Pack 1", "Dungeon Row: Late-game Pack 2"], 
        "RowSanity: Pickaxe": ["Dungeon Row: Gold Pack 2", "Dungeon Row: Tome Pack"], 
        "RowSanity: Rebel Captain": ["Dungeon Row: Speedy Pack 1"], 
        "RowSanity: Rebel Miner": ["Dungeon Row: Gold Pack 1"], 
        "RowSanity: Rebel Scout": ["Dungeon Row: Speedy Pack 2"], 
        "RowSanity: Rebel Soldier": ["Dungeon Row: Mid-tier Pack"], 
        "RowSanity: Ruby": ["Dungeon Row: Gem Pack 1", "Dungeon Row: Gem Pack 2"], 
        "RowSanity: Sapphire": ["Dungeon Row: Gem Pack 2"], 
        "RowSanity: Scepter of the Ape Lord": ["Dungeon Row: Swag Pack 2"], 
        "RowSanity: Search": ["Dungeon Row: Gold Pack 1", "Dungeon Row: Gold Pack 2"], 
        "RowSanity: Silver Spear": ["Dungeon Row: Late-game Pack 1", "Dungeon Row: Control Pack"], 
        "RowSanity: Singing Sword": ["Dungeon Row: Control Pack"], 
        "RowSanity: Sleight of Hand": ["Dungeon Row: Control Pack", "Dungeon Row: Deck Fixing Pack"], 
        "RowSanity: Sneak": ["Dungeon Row: Swag Pack 1", "Dungeon Row: Swag Pack 2"], 
        "RowSanity: Swagger": ["Dungeon Row: Swag Pack 1", "Dungeon Row: Swag Pack 2"], 
        "RowSanity: Tattle": ["Dungeon Row: Skill Pack"], 
        "RowSanity: The Duke": ["Dungeon Row: Gold Pack 2"], 
        "RowSanity: The Mountain King": ["Dungeon Row: Vitality Pack 2"], 
        "RowSanity: The Queen of Hearts": ["Dungeon Row: Mid-tier Pack"], 
        "RowSanity: Treasure Hunter": ["Dungeon Row: Speedy Pack 2", "Dungeon Row: Deck Fixing Pack"], 
        "RowSanity: Treasure Map": ["Dungeon Row: Gold Pack 1"], 
        "RowSanity: Tunnel Guide": ["Dungeon Row: Speedy Pack 1", "Vitality Pack 1"], 
        "RowSanity: Underworld Dealing": ["Dungeon Row: Tome Pack"], 
        "RowSanity: Wand of Recall": ["Dungeon Row: Late-game Pack 1", "Dungeon Row: Late-game Pack 2"], 
        "RowSanity: Wand of Wind": ["Dungeon Row: Late-game Pack 1"], 
        "RowSanity: Wizard": ["Dungeon Row: Tome Pack"], 
        "RowSanity: Animated Door": ["Dungeon Row: Basic Monster Pack 3", "Dungeon Row: Hard Monster Pack 2"], 
        "RowSanity: Dragon Shrine": ["Dungeon Row: Device Pack 3"], 
        "RowSanity: Ladder": ["Dungeon Row: Device Pack 1", "Dungeon Row: Device Pack 2"], 
        "RowSanity: Shrine": ["Dungeon Row: Device Pack 1", "Dungeon Row: Device Pack 2", "Dungeon Row: Device Pack 3"], 
        "RowSanity: Teleporter": ["Dungeon Row: Device Pack 1", "Dungeon Row: Device Pack 2"], 
        "RowSanity: Belcher": ["Dungeon Row: Basic Monster Pack 1", "Dungeon Row: Basic Monster Pack 2"], 
        "RowSanity: Cave Troll": ["Dungeon Row: Hard Monster Pack 1"], 
        "RowSanity: Crystal Golem": ["Dungeon Row: Hard Monster Pack 1", "Dungeon Row: Hard Monster Pack 2"], 
        "RowSanity: Kobold": ["Dungeon Row: Basic Monster Pack 1", "Dungeon Row: Basic Monster Pack 2", "Dungeon Row: Basic Monster Pack 3"], 
        "RowSanity: Ogre": ["Dungeon Row: Hard Monster Pack 1", "Dungeon Row: Hard Monster Pack 2"], 
        "RowSanity: Orc Grunt": ["Dungeon Row: Basic Monster Pack 1", "Dungeon Row: Basic Monster Pack 2", "Dungeon Row: Basic Monster Pack 3"], 
        "RowSanity: Overlord": ["Dungeon Row: Hard Monster Pack 1", "Dungeon Row: Hard Monster Pack 2"], 
        "RowSanity: The Vault": ["Dungeon Row: Device Pack 3"], 
        "RowSanity: Watcher": ["Dungeon Row: Basic Monster Pack 1", "Dungeon Row: Basic Monster Pack 2", "Dungeon Row: Basic Monster Pack 3"]
    },
    "gem_collection_rules": {
        "Gem Collection: Dragon's Eye": ["Dungeon Row: Gem Pack 2"],
        "Gem Collection: Diamond": ["Dungeon Row: Gem Pack 1"],
        "Gem Collection: Emerald": ["Dungeon Row: Gem Pack 1", "Dungeon Row: Gem Pack 2"],
        "Gem Collection: Sapphire": ["Dungeon Row: Gem Pack 1", "Dungeon Row: Gem Pack 2"],
        "Gem Collection: Ruby": ["Dungeon Row: Gem Pack 1", "Dungeon Row: Gem Pack 2"],
    }
}